// name|category|upgrade difficulty|rarity|effect key:value pairs|note
// Sources: Rune Factory Wiki's RF4 Other Items tables and the four Raw Ingredients tables.
export const MATERIAL_ROWS = [
  // Other Items — Minerals
  "Scrap Metal+|Minerals|10|2|def:2|Weapon upgrade only: fixes damage at exactly 1",
  "Iron|Minerals|2|1|def:1|",
  "Bronze|Minerals|15|4|def:4|",
  "Silver|Minerals|32|7|def:7|",
  "Gold|Minerals|40|9|def:10|",
  "Platinum|Minerals|50|12|def:25|",
  "Orichalcum|Minerals|80|13|def:95|",
  "Dragonic Stone|Minerals|95|15|def:160,mdef:120|",

  // Other Items — Jewels
  "Amethyst|Jewels|4|0|mdef:1|",
  "Aquamarine|Jewels|11|2|mdef:3|",
  "Emerald|Jewels|26|5|mdef:5|",
  "Ruby|Jewels|36|7|mdef:8|",
  "Sapphire|Jewels|42|8|mdef:12|",
  "Diamond|Jewels|50|11|mdef:24|",
  "Green Core|Jewels|81|13|mdef:77|Four-core armor set component",
  "Red Core|Jewels|81|13|mdef:77|Four-core armor set component",
  "Yellow Core|Jewels|81|13|mdef:77|Four-core armor set component",
  "Blue Core|Jewels|81|13|mdef:77|Four-core armor set component",
  "Crystal Skull|Jewels|95|15|matk:60,mdef:195|",

  // Other Items — Crystals
  "Magic Crystal|Crystals|27|4|matk:5,mdef:1|",
  "Dark Crystal|Crystals|25|3|str:3,vit:3|Dark weapon element",
  "Fire Crystal|Crystals|25|7|atk:5|Fire weapon element",
  "Wind Crystal|Crystals|25|10|mdef:5|Wind weapon element",
  "Earth Crystal|Crystals|25|8|def:5|Earth weapon element",
  "Water Crystal|Crystals|25|11|matk:5|Water weapon element",
  "Love Crystal|Crystals|50|9|drainAtk:3|Love weapon element",
  "Light Crystal|Crystals|25|12|vit:3,int:3|Light weapon element",
  "Small Crystal|Crystals|80|13|atk:80|",
  "Big Crystal|Crystals|83|13|atk:40,matk:40|",
  "Rune Crystal|Crystals|89|14|matk:100|",
  "Electro Crystal|Crystals|93|15|atk:60,matk:150,mdef:-5,paralysisAtk:35|",

  // Other Items — Sticks and Stems
  "Branch|Sticks and Stems|0|0|atk:1|Upgrade difficulty 0",
  "Lumber|Sticks and Stems|0|0|atk:1|Upgrade difficulty 0",
  "Stick|Sticks and Stems|2|0|atk:2|",
  "Insect Horn|Sticks and Stems|7|1|atk:3|",
  "Plant Stem|Sticks and Stems|28|3|atk:3,matk:3|",
  "Bull's Horn|Sticks and Stems|36|7|atk:7,def:1|",
  "Rigid Horn|Sticks and Stems|52|10|atk:15,crit:1|",
  "Thick Stick|Sticks and Stems|65|12|atk:34|",
  "Devil Horn|Sticks and Stems|86|13|atk:55,matk:50|",
  "Moving Branch|Sticks and Stems|95|9|atk:-10,matk:200|",

  // Other Items — Liquids
  "Glue|Liquids|26|5|atk:1,def:2,mdef:2|",
  "Devil Blood|Liquids|39|9|matk:9,drainRes:15|",
  "Paralysis Poison|Liquids|30|10|poisonAtk:20|",
  "Poison King|Liquids|86|14|atk:5,matk:88,poisonAtk:80|",

  // Other Items — Feathers
  "Bird's Feather|Feathers|10|2|int:2|",
  "Black Bird Feather|Feathers|50|10|int:14|",
  "Thunderbird Feather|Feathers|58|12|int:28|",
  "Yellow Feather|Feathers|90|5|int:130|",
  "Dragon Fin|Feathers|96|15|vit:-10,int:300|",

  // Other Items — Shells and Bones
  "Turtle Shell|Shells and Bones|15|2|def:4,mdef:1,crit:-3|",
  "Fish Fossil|Shells and Bones|20|3|matk:4,mdef:1|",
  "Skull|Shells and Bones|39|9|matk:8,mdef:5,sickAtk:4|",
  "Dragon Bones|Shells and Bones|50|8|def:10,mdef:10,vit:10|",
  "Blk. Tortoise Shell|Shells and Bones|62|12|def:26,mdef:7|Same item as Black Tortoise Shell",
  "Black Tortoise Shell|Shells and Bones|62|12|def:26,mdef:7|Same item as Blk. Tortoise Shell",
  "Ammonite|Shells and Bones|92|15|def:135,mdef:82,str:-5|",

  // Other Items — Stones
  "Rock|Stones|0|0|crit:1|Upgrade difficulty 0",
  "Material Stone|Stones|0|0|crit:1|Upgrade difficulty 0",
  "Round Stone|Stones|25|4|atk:5,crit:5|",
  "Tiny Golem Stone|Stones|38|9|def:8,crit:2|",
  "Golem Stone|Stones|53|12|def:15,crit:3|",
  "Golem Tablet|Stones|80|13|def:30,crit:5|",
  "Golem Spirit Stone|Stones|85|14|def:105,crit:6|",
  "Tablet of Truth|Stones|95|15|atk:50,def:160,matk:20,mdef:-15,crit:10|",

  // Other Items — Strings
  "Yarn|Strings|4|1|def:1,matk:1|",
  "Old Bandage|Strings|11|2|matk:2,mdef:1|",
  "Ambrosia's Thorns|Strings|30|2|atk:7,matk:7,sleepAtk:10|",
  "Spider's Thread|Strings|18|4|atk:2,matk:2,paralysisAtk:5|",
  "Puppetry Strings|Strings|40|6|atk:5,matk:8,sealAtk:15,paralysisAtk:5|",
  "Vine|Strings|30|6|matk:7,sealAtk:4|",
  "Scorpion Tail|Strings|30|7|atk:5,poisonAtk:8|",
  "Strong Vine|Strings|44|10|matk:12,sealAtk:10|",
  "Pretty Thread|Strings|52|12|matk:16,paralysisAtk:25|",
  "Chimera Tail|Strings|95|15|atk:200,matk:-10,poisonAtk:50,paralysisAtk:50|",

  // Other Items — Shards
  "Arrowhead|Shards|3|0|str:1|",
  "Blade Shard|Shards|9|2|str:2|",
  "Broken Hilt|Shards|21|5|def:2,poisonRes:5,sealRes:5,paralysisRes:5,sleepRes:5,fatigueRes:5,sickRes:5|",
  "Broken Box|Shards|44|8|def:4,poisonRes:10,sealRes:10,paralysisRes:10,sleepRes:10,fatigueRes:5,sickRes:5|",
  "Hammer Piece|Shards|37|9|str:6,diz:1|",
  "Shoulder Piece|Shards|45|11|def:11,knock:8|",
  "Rusty Screw|Shards|57|11|matk:25,mdef:-2|",
  "Shiny Screw|Shards|80|11|def:30,matk:40,mdef:10|",
  "Glistening Blade|Shards|66|12|atk:38|",
  "Great Hammer Shard|Shards|60|12|str:30,diz:2|",
  "Pirate's Armor|Shards|84|14|def:83,knock:15|",
  "Left Rock Shard|Shards|88|14|def:120,mdef:35,poisonRes:6,sealRes:6,paralysisRes:6,sleepRes:6,fatigueRes:6,sickRes:6,faintRes:1,drainRes:1|",
  "Right Rock Shard|Shards|88|14|def:35,mdef:120,dizRes:5,critRes:3,knockRes:15|",
  "MTGU Plate|Shards|80|14|def:8,fatigueRes:8,sickRes:8|",
  "Broken Ice Wall|Shards|96|15|atk:105,matk:95,stun:25,sleepRes:10|",

  // Other Items — Furs
  "Fur (S)|Furs|1|0|vit:1,dizRes:1|",
  "Fur (M)|Furs|35|7|def:5,mdef:3,dizRes:10|",
  "Fur (L)|Furs|52|10|def:10,mdef:5,dizRes:25,sleepAtk:3|",
  "Fur|Furs|8|1|def:2,mdef:1,dizRes:2|",
  "Yellow Down|Furs|17|3|def:2,mdef:2,dizRes:5|",
  "Quality Fur|Furs|23|4|def:3,mdef:2,dizRes:10|",
  "Lightning Mane|Furs|35|5|def:7,mdef:6,vit:4,dizRes:20|",
  "Quality Puffy Fur|Furs|36|6|def:5,mdef:3,dizRes:8|",
  "Wooly Furball|Furs|41|9|def:8,mdef:4,dizRes:16,sleepAtk:1|",
  "Penguin Down|Furs|66|11|def:30,mdef:8,dizRes:18|",
  "Red Lion Fur|Furs|92|15|atk:10,def:105,mdef:35,dizRes:20|",
  "Blue Lion Fur|Furs|92|15|def:35,matk:10,mdef:105,dizRes:20|",
  "Chest Hair|Furs|91|15|atk:25,def:110,mdef:60,int:-5,dizRes:25|",

  // Other Items — Powders and Spores
  "Spore|Powders and Spores|8|1|matk:2|",
  "Fairy Dust|Powders and Spores|19|3|matk:5|",
  "Gunpowder|Powders and Spores|27|5|atk:1,matk:5|",
  "Poison Powder|Powders and Spores|20|6|matk:2,mdef:2,poisonAtk:5|",
  "Holy Spore|Powders and Spores|33|7|matk:10,poisonAtk:33,sealAtk:33,paralysisAtk:33,drainRes:50|",
  "Root|Powders and Spores|35|8|matk:8|",
  "Magic Powder|Powders and Spores|40|9|matk:10|",
  "Mysterious Powder|Powders and Spores|55|10|matk:15,fatigueAtk:10,sickAtk:5|",
  "Magic|Powders and Spores|53|11|matk:20|",
  "Fairy Elixir|Powders and Spores|67|12|matk:40|",
  "Earth Dragon Ash|Powders and Spores|80|11|def:33,mdef:33,vit:5|",
  "Fire Dragon Ash|Powders and Spores|80|12|atk:80,str:10|",
  "Water Dragon Ash|Powders and Spores|80|13|matk:80,int:10|",
  "Turnip's Miracle|Powders and Spores|85|14|mdef:99|",
  "Melody Bottle|Powders and Spores|94|15|atk:30,def:-10,matk:170,mdef:30,poisonAtk:10,sealAtk:10,paralysisAtk:10,sleepAtk:10,fatigueAtk:10,sickAtk:10,faintAtk:1|",

  // Other Items — Cloths and Skins
  "Cheap Cloth|Cloths and Skins|2|0|def:1,critRes:1|",
  "Insect Carapace|Cloths and Skins|7|1|def:1,poisonRes:15|",
  "Ghost Hood|Cloths and Skins|24|4|def:3,sealRes:30|",
  "Pretty Carapace|Cloths and Skins|35|6|def:3,sealRes:5,paralysisRes:25|",
  "Quality Cloth|Cloths and Skins|32|7|def:5,critRes:5|",
  "Quality Worn Cloth|Cloths and Skins|83|8|def:52,mdef:35,dizRes:10,critRes:10,sealRes:30|",
  "Silk Cloth|Cloths and Skins|38|9|def:9,critRes:4|",
  "Giant's Gloves|Cloths and Skins|43|10|atk:3,def:8,critRes:6|",
  "Blue Giant's Glove|Cloths and Skins|54|11|atk:6,def:12,critRes:8|",
  "Ancient Orc Cloth|Cloths and Skins|90|14|def:96,mdef:48,dizRes:15,critRes:15,sealRes:30|",

  // Other Items — Claws and Fangs
  "Insect Jaw|Claws and Fangs|4|0|atk:2|",
  "Panther Claw|Claws and Fangs|20|4|atk:4|",
  "Wolf Fang|Claws and Fangs|30|5|atk:6|",
  "Palm Claw|Claws and Fangs|32|6|atk:8|",
  "Giant's Nail|Claws and Fangs|40|7|atk:10|",
  "Chimera's Claw|Claws and Fangs|45|7|atk:15,matk:2,poisonAtk:5,paralysisAtk:5|",
  "Ivory Tusk|Claws and Fangs|50|8|atk:16,def:-5,matk:1|",
  "Big Giant's Nail|Claws and Fangs|90|9|atk:150|",
  "Unbroken Ivory Tusk|Claws and Fangs|55|10|atk:19,matk:2|",
  "Gold Wolf Fang|Claws and Fangs|61|11|atk:26|",
  "Scorpion Pincer|Claws and Fangs|60|11|atk:30,def:-5|",
  "Cheap Propeller|Claws and Fangs|62|11|atk:29,def:-2|",
  "Quality Propeller|Claws and Fangs|69|12|atk:40,def:5|",
  "Magic Claw|Claws and Fangs|74|12|atk:42,matk:15|",
  "Dragon Fang|Claws and Fangs|80|13|atk:60|",
  "Malm Claw|Claws and Fangs|88|14|atk:121|",
  "Queen's Jaw|Claws and Fangs|89|14|atk:100,def:10,matk:40,mdef:10|",
  "Dangerous Scissors|Claws and Fangs|90|14|atk:195,def:-50|",
  "Wind Dragon Tooth|Claws and Fangs|98|15|atk:180,matk:180|",

  // Other Items — Scales
  "Wet Scale|Scales|58|11|vit:22|",
  "Dragon Scale|Scales|88|14|str:10,vit:140|",
  "Crimson Scale|Scales|88|14|str:140,vit:10|",
  "Blue Scale|Scales|88|14|vit:10,int:140|",
  "Glitter Scale|Scales|88|14|str:70,vit:10,int:70|",
  "Love Scale|Scales|88|14|str:50,vit:50,int:50|",
  "Black Scale|Scales|88|14|str:10,vit:70,int:70|",
  "Grimoire Scale|Scales|95|15|str:50,vit:160,int:50|",
  "Firewyrm Scale|Scales|96|15|str:300,int:-10|",
  "Earthwyrm Scale|Scales|96|15|str:-10,vit:300|",
  "Legendary Scale|Scales|90|15|drainAtk:10|",

  // Other Items — Misc.
  "Scrap Metal|Minerals|1|0|def:-2|",
  "Double Steel|Misc.|50|5||Adds 2× the prior material's printed effect; once per item",
  "10-Fold Steel|Misc.|95|10||Adds 8× the prior material's printed effect; once per item",
  "Glitta Augite|Misc.|50|8||Weapon upgrade only: range +0.5; stacks with Raccoon Leaf",
  "Invisible Stone|Misc.|33|5||Makes the finished item invisible",
  "Light Ore|Misc.|50|13||Crafting only: enables base-stat overrides between different Weapon or Staff categories",
  "Rune Sphere Shard|Misc.|99|15|str:120,vit:120,int:120|",
  "Shade Stone|Misc.|40|6||Decreases enemy tolerance on hit",
  "Raccoon Leaf|Misc.|65|10|int:40|Weapon upgrade only: range +0.25; stacks with Glitta Augite",
  "Icy Nose|Misc.|92|15|atk:128,matk:90,int:-5,diz:1,crit:2,stun:5|",
  "Big Bird's Comb|Misc.|65|10|atk:22,faintRes:50|",
  "Rafflesia Petal|Misc.|55|9|atk:7,matk:17,fatigueAtk:20,sickAtk:15|",
  "Cursed Doll|Misc.|40|6|def:4,mdef:7,sealRes:15,paralysisRes:15,drainRes:20|",
  "Warrior's Proof|Misc.|77|13|str:58,int:5,faintRes:15|",
  "Proof of Rank|Misc.|77|13|str:15,int:48,faintRes:15|",
  "Throne of the Empire|Misc.|97|14|int:-5,knock:30|",
  "White Stone|Misc.|30|13||Greatly reduces damage when used on a family member's equipment",
  "Rare Can|Misc.|5|0||Weapon upgrade only: increases rare-item drop rate by approximately 3%; stacks with one Clover effect but not another Rare Can",

  // Other Items — Grasses
  "Withered Grass|Grasses|1|0|vit:-1|Also improves soil quality when tilled",
  "Weeds|Grasses|1|0||",
  "Medicinal Herb|Grasses|2|0|fatigueRes:1|",
  "Antidote Grass|Grasses|8|0|poisonRes:3|",
  "Green Grass|Grasses|1|0||",
  "Blue Grass|Grasses|11|0||",
  "Purple Grass|Grasses|5|1||",
  "Black Grass|Grasses|23|3||",
  "Indigo Grass|Grasses|29|4||",
  "Yellow Grass|Grasses|39|5||",
  "Red Grass|Grasses|40|6||",
  "Orange Grass|Grasses|48|7||",
  "White Grass|Grasses|65|8||",

  // Consumables — Raw Ingredients: Regular Crops
  "Turnip|Raw Ingredients|1|0|str:1|Regular crop",
  "Potato|Raw Ingredients|7|1|vit:2|Regular crop",
  "Spinach|Raw Ingredients|9|1|matk:2|Regular crop",
  "Radish|Raw Ingredients|12|2|vit:3|Regular crop",
  "Cucumber|Raw Ingredients|17|3|str:2|Regular crop",
  "Yam|Raw Ingredients|18|3|vit:5|Regular crop",
  "Pumpkin|Raw Ingredients|19|3|str:3|Regular crop",
  "Pink Turnip|Raw Ingredients|21|3|str:4|Regular crop",
  "Strawberry|Raw Ingredients|24|4|str:3,vit:3|Regular crop",
  "Corn|Raw Ingredients|27|4|vit:6|Regular crop",
  "Carrot|Raw Ingredients|27|4|vit:7|Regular crop",
  "Orange|Raw Ingredients|30|5|vit:4,int:4|Regular crop",
  "Grapes|Raw Ingredients|30|5|str:4,vit:4|Regular crop",
  "Green Pepper|Raw Ingredients|31|5|str:6|Regular crop",
  "Apple|Raw Ingredients|32|5|str:4,int:4|Regular crop",
  "Eggplant|Raw Ingredients|33|5|str:7|Regular crop",
  "Leek|Raw Ingredients|35|5|matk:6|Regular crop",
  "Hot-Hot Fruit|Raw Ingredients|35|5|mdef:7,fireRes:5|Regular crop",
  "Bok Choy|Raw Ingredients|36|6|matk:8|Regular crop",
  "Cabbage|Raw Ingredients|37|6|int:6|Regular crop",
  "Onion|Raw Ingredients|37|6|vit:10|Regular crop",
  "Tomato|Raw Ingredients|43|7|str:9|Regular crop",
  "Pink Melon|Raw Ingredients|45|7|int:7|Regular crop",
  "Pineapple|Raw Ingredients|50|8|str:15|Regular crop",
  "Golden Potato|Raw Ingredients|55|9|vit:30,faintAtk:1|Regular crop",
  "Golden Pumpkin|Raw Ingredients|56|9|str:25,faintAtk:1|Regular crop",
  "Golden Cabbage|Raw Ingredients|59|9|int:20,faintAtk:1|Regular crop",
  "Golden Turnip|Raw Ingredients|67|10|str:30,faintAtk:1|Regular crop",

  // Consumables — Raw Ingredients: Giant Crops
  "Tyrant Turnip|Raw Ingredients|25|4|str:5,loveRes:15|Giant crop",
  "Princely Potato|Raw Ingredients|34|5|vit:9|Giant crop",
  "Sovereign Spinach|Raw Ingredients|35|5|matk:7|Giant crop",
  "Noble Radish|Raw Ingredients|38|6|vit:12|Giant crop",
  "Kaiser Cucumber|Raw Ingredients|42|7|str:8|Giant crop",
  "Lordly Yam|Raw Ingredients|44|7|vit:15|Giant crop",
  "Doom Pumpkin|Raw Ingredients|45|7|str:10|Giant crop",
  "Colossal Pink|Raw Ingredients|47|7|str:12|Giant crop",
  "Sultan Strawberry|Raw Ingredients|49|8|str:8,vit:8|Giant crop",
  "Gigant Corn|Raw Ingredients|49|8|vit:17|Giant crop",
  "Royal Carrot|Raw Ingredients|51|8|vit:21|Giant crop",
  "Green Pepper Rex|Raw Ingredients|53|9|str:16|Giant crop",
  "Emperor Eggplant|Raw Ingredients|54|9|str:17|Giant crop",
  "Legendary Leek|Raw Ingredients|54|9|matk:11|Giant crop",
  "Giant Hot-Hot Fruit|Raw Ingredients|55|9|mdef:11,fireRes:15|Giant crop",
  "Boss Bok Choy|Raw Ingredients|60|10|matk:21|Giant crop",
  "King Cabbage|Raw Ingredients|61|10|int:22|Giant crop",
  "Ultra Onion|Raw Ingredients|62|10|vit:35|Giant crop",
  "Titan Tomato|Raw Ingredients|66|11|str:28|Giant crop",
  "Conqueror Melon|Raw Ingredients|69|11|int:31|Giant crop",
  "King Pineapple|Raw Ingredients|72|12|atk:35|Giant crop",
  "Gold Prince Potato|Raw Ingredients|70|13|vit:80,faintAtk:2|Giant crop",
  "Golden Doom Pumpkin|Raw Ingredients|79|13|str:50,faintAtk:2|Giant crop",
  "Golden King Cabbage|Raw Ingredients|82|13|int:50,faintAtk:2|Giant crop",
  "Golden Tyrant Turnip|Raw Ingredients|91|14|str:90,faintAtk:2|Giant crop",

  // Consumables — Raw Ingredients: Regular Flowers
  "Toyherb|Raw Ingredients|1|0|vit:1,fatigueRes:5|Regular flower",
  "Moondrop|Raw Ingredients|10|1|int:1|Regular flower",
  "Pink Cat|Raw Ingredients|15|2|int:2|Regular flower",
  "Charm Blue|Raw Ingredients|20|3|poisonAtk:5|Regular flower",
  "Cherry Grass|Raw Ingredients|22|3|sleepAtk:1|Regular flower",
  "Pom-Pom Grass|Raw Ingredients|28|4|poisonAtk:3,poisonRes:5|Regular flower",
  "Lamp Grass|Raw Ingredients|28|4|int:3|Regular flower",
  "Ironleaf|Raw Ingredients|29|4|atk:4|Regular flower",
  "4-Leaf Clover|Raw Ingredients|29|4||Equipment upgrade only: increases item drop rate by approximately 11%; does not stack with another Clover",
  "Autumn Grass|Raw Ingredients|35|5|sleepRes:6|Regular flower",
  "Noel Grass|Raw Ingredients|41|6|int:7|Regular flower",
  "Fireflower|Raw Ingredients|41|6|str:2,int:6|Regular flower",
  "Blue Crystal|Raw Ingredients|53|8|matk:10,mdef:10,waterRes:5|Regular flower",
  "Green Crystal|Raw Ingredients|53|8|mdef:20,windRes:5|Regular flower",
  "Red Crystal|Raw Ingredients|53|8|matk:20,fireRes:5|Regular flower",
  "White Crystal|Raw Ingredients|53|8|int:20,earthRes:5|Regular flower",
  "Elli Leaves|Grasses|60|10||Source lists upgrade effect as unknown",
  "Emery Flower|Raw Ingredients|66|10|int:30|Regular flower",

  // Consumables — Raw Ingredients: Giant Flowers
  "Ultra Toyherb|Raw Ingredients|26|4|fatigueRes:30|Giant flower",
  "Ultra Moondrop Flower|Raw Ingredients|35|5|int:4|Giant flower",
  "King Pink Cat|Raw Ingredients|38|6|int:5|Giant flower",
  "Great Charm Blue|Raw Ingredients|46|7|int:8,poisonAtk:17|Giant flower",
  "King Cherry Grass|Raw Ingredients|47|7|sleepAtk:9|Giant flower",
  "King Pom-Pom Grass|Raw Ingredients|52|8|poisonAtk:15,poisonRes:19|Giant flower",
  "Kaiser Lamp Grass|Raw Ingredients|52|8|int:10|Giant flower",
  "Super Ironleaf|Raw Ingredients|52|8|atk:18|Giant flower",
  "Great 4-Leaf Clover|Raw Ingredients|52|8||Giant 4-Leaf Clover; same equipment-upgrade item-drop effect as 4-Leaf Clover with higher rarity only",
  "Giant 4-Leaf Clover|Raw Ingredients|52|8||Alias of Great 4-Leaf Clover; same equipment-upgrade item-drop effect as 4-Leaf Clover with higher rarity only",
  "Big Autumn Grass|Raw Ingredients|57|9|sleepRes:25|Giant flower",
  "Large Noel Grass|Raw Ingredients|63|10|int:22|Giant flower",
  "Big Fireflower|Raw Ingredients|64|10|str:10,int:18|Giant flower",
  "Big Blue Crystal|Raw Ingredients|73|12|matk:30,mdef:30,waterRes:20|Giant flower",
  "Big Green Crystal|Raw Ingredients|74|12|mdef:60,windRes:20|Giant flower",
  "Big Red Crystal|Raw Ingredients|75|12|matk:60,fireRes:20|Giant flower",
  "Big White Crystal|Raw Ingredients|76|12|int:60,earthRes:20|Giant flower",
  "Great Emery Flower|Raw Ingredients|95|15|int:80|Giant flower",
] as const;
