// Transcribed from the Rune Factory Wiki RF4 Forging and Crafting recipe tables.
// Format: group | item | skill level | semicolon-separated required materials.
export const RECIPE_ROWS = [
  // Forging — short swords
  "Short Sword|Broadsword|1|Minerals",
  "Short Sword|Steel Sword|3|Minerals;Claws and Fangs",
  "Short Sword|Steel Sword+|4|Steel Sword;Minerals",
  "Short Sword|Cutlass|7|Bronze;Claws and Fangs",
  "Short Sword|Aqua Sword|15|Silver;Aquamarine",
  "Short Sword|Invisiblade|16|Invisible Stone;Claws and Fangs;Crystals",
  "Short Sword|Defender|19|Sapphire;Claws and Fangs",
  "Short Sword|Burning Sword|20|Gold;Fire Crystal",
  "Short Sword|Back Scratcher|20|Glue;Sticks and Stems",
  "Short Sword|Gorgeous Sword|23|Gold;Gold;Gold;Gold",
  "Short Sword|Spoon|25|Silver;Silver",
  "Short Sword|Gaia Sword|27|Gold;Earth Crystal;Rigid Horn",
  "Short Sword|Snakesword|30|Diamond;Claws and Fangs",
  "Short Sword|Veggieblade|32|Carrot",
  "Short Sword|Luck Blade|35|Diamond;Scorpion Pincer;Claws and Fangs",
  "Short Sword|Platinum Sword|38|Platinum;Silver;Claws and Fangs;Sticks and Stems",
  "Short Sword|Wind Sword|40|Platinum;Silver;Wind Crystal",
  "Short Sword|Chaos Blade|42|Platinum;Gold;Magic;Holy Spore",
  "Short Sword|Sakura|44|Platinum;Paralysis Poison;Poison Powder;Cherry Grass",
  "Short Sword|Sunspot|46|Platinum;Gold;Warrior's Proof;Fire Crystal;Ruby",
  "Short Sword|Durendal|50|Platinum;Platinum;Malm Claw;Devil Horn;Ambrosia's Thorns",
  "Short Sword|Aerial Blade|54|Orichalcum;Lightning Mane;Wind Crystal;Emerald;Claws and Fangs",
  "Short Sword|Grantale|59|Orichalcum;Yellow Feather;Earth Crystal;Amethyst;Cursed Doll",
  "Short Sword|Smash Blade|64|Orichalcum;Pirate's Armor;4-Leaf Clover;Chimera's Claw;Claws and Fangs",
  "Short Sword|Icifier|68|Orichalcum;Icy Nose;Water Crystal;Aquamarine;Claws and Fangs",
  "Short Sword|Soul Eater|70|Orichalcum;Dangerous Scissors;Love Crystal;Legendary Scale;Earth Dragon Ash",
  "Short Sword|Raventine|74|Orichalcum;Orichalcum;Golem Spirit Stone;Fire Crystal;Fire Dragon Ash",
  "Short Sword|Star Saber|77|Orichalcum;Golem Spirit Stone;Wind Crystal;Emerald;Electro Crystal",
  "Short Sword|Platinum Sword+|79|Platinum Sword;Dragonic Stone",
  "Short Sword|Dragon Slayer|82|Dragonic Stone;Dragonic Stone;Black Scale;Blue Scale;Glitter Scale",
  "Short Sword|Rune Blade|85|Dragonic Stone;Earthwyrm Scale;Rune Crystal;Claws and Fangs;Sticks and Stems",
  "Short Sword|Gladius|90|Dragonic Stone;Firewyrm Scale;Small Crystal;Throne of the Empire;Claws and Fangs",
  "Short Sword|Rune Legend|99|Rune Sphere Shard;Dragonic Stone;Rune Crystal;Green Core;Wind Dragon Tooth",

  // Forging — long swords
  "Long Sword|Claymore|2|Minerals",
  "Long Sword|Zweihaender|6|Minerals;Claws and Fangs",
  "Long Sword|Zweihaender+|11|Zweihaender;Bronze",
  "Long Sword|Great Sword|16|Bronze;Liquids",
  "Long Sword|Sea Cutter|21|Silver;Aquamarine",
  "Long Sword|Cyclone Blade|25|Gold;Emerald",
  "Long Sword|Poison Blade|27|Gold;Silver;Poison Powder",
  "Long Sword|Katzbalger|29|Gold;Silver;Rigid Horn",
  "Long Sword|Earth Shade|30|Gold;Silver;Black Bird Feather;Earth Crystal",
  "Long Sword|Big Knife|32|Diamond;Claws and Fangs;Sticks and Stems",
  "Long Sword|Katana|35|Diamond;Magic;Claws and Fangs",
  "Long Sword|Flame Saber|39|Diamond;Gold Wolf Fang;Fire Crystal",
  "Long Sword|Bio Smasher|40|Platinum;Paralysis Poison;Poison Powder;Pom-Pom Grass",
  "Long Sword|Snow Crown|42|Platinum;Gold;Water Crystal;Aquamarine",
  "Long Sword|Dancing Dicer|43|Platinum;Dragon Fang;Dragon Bones",
  "Long Sword|Flamberge|45|Platinum;Platinum;Magic Claw;Thunderbird Feather;Big Bird's Comb",
  "Long Sword|Flamberge+|46|Flamberge;Malm Claw",
  "Long Sword|Volcanon|48|Devil Horn;Fire Crystal;Ruby;Chimera's Claw",
  "Long Sword|Psycho|50|Devil Horn;Malm Claw;Dark Crystal;Rafflesia Petal",
  "Long Sword|Shine Blade|52|Orichalcum;Platinum;Light Crystal;Sapphire",
  "Long Sword|Grand Smasher|55|Yellow Feather;Earth Crystal;Ambrosia's Thorns;Earth Dragon Ash",
  "Long Sword|Belzebuth|58|Ammonite;Devil Blood;Dark Crystal",
  "Long Sword|Orochi|63|Queen's Jaw;Grimoire Scale;Scales;Scales;Strings",
  "Long Sword|Punisher|68|Dangerous Scissors;Tablet of Truth;Minerals",
  "Long Sword|Steel Slicer|73|Orichalcum;Orichalcum;Golem Spirit Stone;MTGU Plate",
  "Long Sword|Moon Shadow|76|Glitter Scale;Light Crystal;Earth Crystal;Red Lion Fur;Blue Lion Fur",
  "Long Sword|Blue-Eyed Blade|79|Dragonic Stone;Orichalcum;Blue Core;Claws and Fangs",
  "Long Sword|Balmung|84|Dragonic Stone;Tablet of Truth;Golem Tablet;Claws and Fangs",
  "Long Sword|Braveheart|89|Dragonic Stone;Earthwyrm Scale;Love Scale;Light Crystal;Sapphire",
  "Long Sword|Force Element|91|Firewyrm Scale;Green Core;Red Core;Yellow Core;Blue Core",
  "Long Sword|Heaven Asunder|92|Rune Sphere Shard;Dragonic Stone;Water Dragon Ash;Fire Dragon Ash;Earth Dragon Ash",
  "Long Sword|Caliburn|99|Rune Sphere Shard;Wind Dragon Tooth;Dragon Fin;Earthwyrm Scale;Firewyrm Scale",
  "Long Sword|Dekash|42|Tuna",
  "Long Sword|Daicone|28|Radish",

  // Forging — spears
  "Spear|Spear|3|Minerals",
  "Spear|Wood Staff|6|Sticks and Stems",
  "Spear|Lance|9|Minerals;Sticks and Stems",
  "Spear|Lance+|12|Lance;Bronze",
  "Spear|Safety Lance|13|Ghost Hood;Sticks and Stems",
  "Spear|Pitchfork|14|Wolf Fang;Fodder;Sticks and Stems",
  "Spear|Needle Spear|15|Bronze;Wolf Fang;Sticks and Stems",
  "Spear|Trident|18|Silver;Sticks and Stems",
  "Spear|Water Spear|21|Silver;Aquamarine;Sticks and Stems",
  "Spear|Halberd|25|Gold;Sticks and Stems",
  "Spear|Corsesca|27|Gold;Rigid Horn;Sticks and Stems",
  "Spear|Corsesca+|29|Corsesca;Black Bird Feather",
  "Spear|Poison Spear|30|Diamond;Poison Powder;Sticks and Stems",
  "Spear|Fivestaff|34|Diamond;Sticks and Stems;Scales;Scales",
  "Spear|Heavy Lance|37|Platinum;Gold;Sticks and Stems",
  "Spear|Feather Lance|38|Platinum;Silver;Thick Stick;Wind Crystal;Feathers",
  "Spear|Iceberg|41|Platinum;Platinum;Thick Stick;Water Crystal;Aquamarine",
  "Spear|Blood Lance|43|Platinum;Cursed Doll;Thick Stick;Magic Claw;Devil Blood",
  "Spear|Magical Lance|47|Devil Horn;Cursed Doll;Puppetry Strings;Round Stone;Crystals",
  "Spear|Flare Lance|49|Platinum;Devil Horn;Proof of Rank;Fire Crystal;Dragon Bones",
  "Spear|Brionac|51|Orichalcum;Light Crystal;Sapphire;Lightning Mane;Sticks and Stems",
  "Spear|Poison Queen|55|Orichalcum;Orichalcum;Poison King;Holy Spore;Poison Powder",
  "Spear|Monk Staff|57|Orichalcum;Turnip's Miracle;Glitta Augite;Sticks and Stems",
  "Spear|Metus|60|Orichalcum;Queen's Jaw;Cursed Doll;Legendary Scale;Sticks and Stems",
  "Spear|Silent Grave|65|Orichalcum;Dangerous Scissors;Crystal Skull;Shards;Sticks and Stems",
  "Spear|Overbreak|69|Blue Scale;Left Rock Shard;Right Rock Shard;Grimoire Scale;Sticks and Stems",
  "Spear|Bjor|74|Melody Bottle;Holy Spore;Orichalcum;Small Crystal;Sticks and Stems",
  "Spear|Belvarose|76|Dragonic Stone;Ambrosia's Thorns;Tablet of Truth;MTGU Plate;Sticks and Stems",
  "Spear|Gae Bolg|81|Dragonic Stone;Orichalcum;Grimoire Scale;Black Scale;Moving Branch",
  "Spear|Dragon's Fang|86|Earthwyrm Scale;Big Crystal;Rune Crystal;Sticks and Stems",
  "Spear|Gungnir|91|Dragon Fin;Green Core;Earth Dragon Ash;Fire Dragon Ash;Sticks and Stems",
  "Spear|Legion|99|Rune Sphere Shard;Firewyrm Scale;Dragon Fin;Light Ore;Sticks and Stems",
  "Spear|Pine Club|40|Pineapple;Sticks and Stems",

  // Forging — axes
  "Axe|Battle Axe|6|Minerals;Claws and Fangs",
  "Axe|Axe|9|Cheap Axe;Minerals",
  "Axe|Battle Scythe|13|Bronze;Claws and Fangs",
  "Axe|Pole Axe|16|Wolf Fang;Bronze;Sticks and Stems",
  "Axe|Pole Axe+|20|Pole Axe;Silver",
  "Axe|Great Axe|23|Gold;Claws and Fangs",
  "Axe|Tomahawk|28|Silver;Emerald;Silk Cloth;Claws and Fangs",
  "Axe|Basilisk Fang|30|Gold;Paralysis Poison;Claws and Fangs;Claws and Fangs",
  "Axe|Rock Axe|32|Gold;Silver;Giant's Gloves;Earth Crystal",
  "Axe|Demon Axe|35|Diamond;Scorpion Pincer;Devil Blood",
  "Axe|Frost Axe|42|Platinum;Dragon Fang;Big Crystal;Water Crystal;Aquamarine",
  "Axe|Crescent Axe|46|Platinum;Chimera's Claw;Devil Horn",
  "Axe|Crescent Axe+|47|Crescent Axe;Warrior's Proof;Proof of Rank",
  "Axe|Heat Axe|53|Orichalcum;Fire Crystal;Ruby;Fire Dragon Ash",
  "Axe|Double Edge|65|Big Giant's Nail;Queen's Jaw;Red Lion Fur;Blue Lion Fur",
  "Axe|Alldale|69|Orichalcum;Orichalcum;Dangerous Scissors;White Stone;Yellow Core",
  "Axe|Devil Finger|73|Love Scale;Legendary Scale;Water Dragon Ash;Fire Dragon Ash;Earth Dragon Ash",
  "Axe|Executioner|81|Dragonic Stone;Golem Spirit Stone;Light Ore;Chimera Tail;Dark Crystal",
  "Axe|Saint Axe|98|Rune Sphere Shard;Light Crystal;White Crystal;Small Crystal;Big Crystal",
  "Axe|Lollipop|28|Butter;Apple",

  // Forging — hammers
  "Hammer|Battle Hammer|3|Minerals",
  "Hammer|Hammer|7|Cheap Hammer;Minerals",
  "Hammer|Toy Hammer|8|Sticks and Stems;Cloths and Skins",
  "Hammer|Bat|9|Bronze",
  "Hammer|War Hammer|11|Bronze;Shards",
  "Hammer|War Hammer+|15|War Hammer;Liquids",
  "Hammer|Iron Bat|18|Bat;Silver",
  "Hammer|Great Hammer|22|Silver;Shards",
  "Hammer|Ice Hammer|26|Gold;Aquamarine;Shards",
  "Hammer|Bone Hammer|31|Gold;Giant's Gloves;Shells and Bones;Shells and Bones",
  "Hammer|Strong Stone|33|Diamond;Stones;Scales;Strings",
  "Hammer|Flame Hammer|36|Diamond;Fire Crystal;Ruby;Shards",
  "Hammer|Gigant Hammer|38|Platinum;Gold;Silver;Shards",
  "Hammer|Sky Hammer|40|Platinum;Wind Crystal;Emerald;Thunderbird Feather",
  "Hammer|Graviton Hammer|49|Grimoire Scale;Earth Crystal;Minerals",
  "Hammer|Spiked Hammer|50|Left Rock Shard;Right Rock Shard;Claws and Fangs;Sticks and Stems",
  "Hammer|Crystal Hammer|57|Orichalcum;Crystal Skull;Big Crystal;Shards",
  "Hammer|Schnabel|60|Orichalcum;Ammonite;Blue Core;Shards",
  "Hammer|Gigant Hammer+|71|Gigant Hammer;Golem Spirit Stone;Orichalcum;Small Crystal",
  "Hammer|Kongo|77|Strong Stone;Dragonic Stone;Small Crystal",
  "Hammer|Mjolnir|86|Earthwyrm Scale;Dragonic Stone;Small Crystal;Rune Crystal",
  "Hammer|Fatal Crush|90|Wind Dragon Tooth;Throne of the Empire;Dragonic Stone;Dragonic Stone;Dragonic Stone",
  "Hammer|Splash Star|99|Rune Sphere Shard;Wind Dragon Tooth;Dragon Fin;Earthwyrm Scale;Firewyrm Scale",

  // Forging — dual blades
  "Dual Blades|Short Dagger|5|Minerals;Minerals",
  "Dual Blades|Steel Edge|9|Iron;Iron;Bronze",
  "Dual Blades|Frost Edge|13|Aquamarine;Aquamarine;Liquids",
  "Dual Blades|Iron Edge|21|Iron;Iron;Silver",
  "Dual Blades|Thief Knife|23|Silver;Silver",
  "Dual Blades|Wind Edge|25|Emerald;Emerald;Palm Claw",
  "Dual Blades|Gorgeous Lx|28|Gorgeous Sword;Gorgeous Sword",
  "Dual Blades|Steel Katana|30|Gold;Gold;Black Bird Feather",
  "Dual Blades|Twin Blade|32|Gold;Gold;Rigid Horn;Rigid Horn;Paralysis Poison",
  "Dual Blades|Rampage|33|Diamond;Diamond;Gold Wolf Fang",
  "Dual Blades|Salamander|35|Diamond;Diamond;Fire Crystal;Cheap Propeller",
  "Dual Blades|Platinum Edge|37|Platinum;Platinum;Dragon Fang;Dragon Fang",
  "Dual Blades|Sonic Dagger|39|Platinum;Platinum;Emerald;Emerald;Thunderbird Feather",
  "Dual Blades|Chaos Edge|40|Platinum;Platinum;Quality Propeller;Quality Propeller;Holy Spore",
  "Dual Blades|Desert Wind|44|Malm Claw;Wind Crystal;Earth Crystal;MTGU Plate",
  "Dual Blades|Broken Wall|48|Left Rock Shard;Right Rock Shard;Earth Crystal",
  "Dual Blades|Force Divide|51|Orichalcum;Fire Crystal;Water Crystal;Red Core;Blue Core",
  "Dual Blades|Heart Fire|54|Fire Dragon Ash;Fire Dragon Ash;Yellow Feather;Fire Crystal",
  "Dual Blades|Orcus Sword|57|Turnip's Miracle;Earth Dragon Ash;Earth Dragon Ash;Glitta Augite;Glitta Augite",
  "Dual Blades|Deep Blizzard|63|Icy Nose;Icy Nose;Water Crystal;Water Crystal",
  "Dual Blades|Dark Invitation|68|Dangerous Scissors;Blue Lion Fur;Red Lion Fur;Legendary Scale;Dark Crystal",
  "Dual Blades|Priest Saber|72|Dangerous Scissors;MTGU Plate;MTGU Plate;Light Crystal;Light Crystal",
  "Dual Blades|Efreet|74|Red Core;Crimson Scale;Golem Spirit Stone;Fire Dragon Ash;Fire Dragon Ash",
  "Dual Blades|Dragoon Claw|76|Dragon Fang;Blue Scale;Glitter Scale;Grimoire Scale;Small Crystal",
  "Dual Blades|Emerald Edge|79|Dragonic Stone;Green Core;Green Core",
  "Dual Blades|Rune Edge|87|Dragonic Stone;Rune Crystal;Rune Crystal",
  "Dual Blades|Earnest Edge|90|Dragonic Stone;Earthwyrm Scale;Earthwyrm Scale;Glitta Augite;Glitta Augite",
  "Dual Blades|Twin Justice|99|Rune Sphere Shard;Firewyrm Scale;Dragon Fin;Fire Dragon Ash;Water Dragon Ash",
  "Dual Blades|Double Scratch|12|Back Scratcher;Back Scratcher",
  "Dual Blades|Acutorimass|23|Silver;Silver;Iron;Iron",
  "Dual Blades|Twin Leeks|39|Leek;Leek",

  // Forging — gloves
  "Gloves|Leather Gloves|2|Cloths and Skins",
  "Gloves|Brass Knuckles|10|Bronze;Cloths and Skins",
  "Gloves|Kote|16|Iron;Palm Claw;Cloths and Skins",
  "Gloves|Gloves|20|Quality Cloth;Fur (M);Strings",
  "Gloves|Bear Claws|28|Gold;Cloths and Skins",
  "Gloves|Fists of the Earth|30|Gold;Rigid Horn;Earth Crystal;Cloths and Skins",
  "Gloves|Fists of Fire|33|Diamond;Fire Crystal;Cloths and Skins",
  "Gloves|Fists of Water|38|Platinum;Water Crystal;Aquamarine;Cloths and Skins",
  "Gloves|Dragon Claws|42|Platinum;Dragon Fang;Scales;Cloths and Skins",
  "Gloves|Fists of Dark|46|Malm Claw;Dark Crystal;Cursed Doll",
  "Gloves|Fists of Wind|50|Malm Claw;Wind Crystal;Chimera's Claw",
  "Gloves|Fists of Light|53|Orichalcum;Light Crystal;Light Crystal;Big Crystal",
  "Gloves|Cat Punch|57|Orichalcum;Quality Worn Cloth;Yellow Feather;Big Bird's Comb;Chimera's Claw",
  "Gloves|Animal Puppets|60|Turnip's Miracle;Rune Crystal;Puppetry Strings;Furs;Furs",
  "Gloves|Ironleaf Fists|64|Orichalcum;Crimson Scale;MTGU Plate;Ironleaf;Ironleaf",
  "Gloves|Caestus|69|Orichalcum;Dangerous Scissors;Red Lion Fur;Blue Lion Fur",
  "Gloves|Golem Punch|75|Orichalcum;Golem Spirit Stone;Golem Tablet;MTGU Plate;Shiny Screw",
  "Gloves|Hand of God|82|Dragonic Stone;Chimera Tail;Ambrosia's Thorns;Small Crystal;Cloths and Skins",
  "Gloves|Bazal Katar|90|Dragonic Stone;Earthwyrm Scale;Firewyrm Scale;Crystal Skull;Cloths and Skins",
  "Gloves|Fenrir|99|Rune Sphere Shard;Rune Crystal;Red Lion Fur;Blue Lion Fur;Broken Ice Wall",

  // Forging — staves
  "Staff|Rod|2|Sticks and Stems",
  "Staff|Amethyst Rod|6|Amethyst;Sticks and Stems",
  "Staff|Aquamarine Rod|8|Aquamarine;Sticks and Stems",
  "Staff|Friendly Rod|13|Love Crystal;Sticks and Stems",
  "Staff|Love-Love Rod|15|Friendly Rod;Love Crystal;Love Crystal;Love Crystal",
  "Staff|Staff|16|Magic Crystal;Sticks and Stems",
  "Staff|Emerald Rod|18|Emerald;Sticks and Stems",
  "Staff|Silver Staff|21|Silver;Sticks and Stems",
  "Staff|Flare Staff|22|Fire Crystal;Sticks and Stems",
  "Staff|Ruby Rod|23|Ruby;Sticks and Stems",
  "Staff|Sapphire Rod|26|Sapphire;Sticks and Stems",
  "Staff|Earth Staff|28|Earth Crystal;Sticks and Stems",
  "Staff|Lightning Wand|30|Wind Crystal;Sticks and Stems",
  "Staff|Ice Staff|31|Water Crystal;Sticks and Stems",
  "Staff|Diamond Rod|33|Diamond;Sticks and Stems",
  "Staff|Wizard's Staff|35|Magic;Sticks and Stems",
  "Staff|Mage's Staff|40|Platinum;Sticks and Stems",
  "Staff|Shooting Star Staff|43|Fairy Elixir;Golem Stone;Sticks and Stems",
  "Staff|Hell Branch|49|Skull;Warrior's Proof;Proof of Rank;Devil Horn",
  "Staff|Crimson Staff|50|Red Core;Fire Dragon Ash;Devil Horn",
  "Staff|Bubble Staff|53|Blue Core;Water Dragon Ash;Orichalcum;Sticks and Stems",
  "Staff|Gaia Rod|56|Yellow Core;Earth Dragon Ash;Yellow Feather;Sticks and Stems",
  "Staff|Cyclone Rod|60|Green Core;Grimoire Scale;Turnip's Miracle;Sticks and Stems",
  "Staff|Storm Wand|65|Mealy Apple;Electro Crystal;Orichalcum;Sticks and Stems",
  "Staff|Rune Staff|70|Rune Crystal;Rune Crystal;Crimson Scale;Sticks and Stems",
  "Staff|Mage's Staff+|76|Dragonic Stone;Orichalcum;Love Scale;Love Crystal;Sticks and Stems",
  "Staff|Magic Broom|82|Ancient Orc Cloth;Moving Branch;Rune Crystal;Big Crystal;Strings",
  "Staff|Magic Shot|85|Earthwyrm Scale;Melody Bottle;Rune Crystal;Small Crystal;Sticks and Stems",
  "Staff|Hell Curse|87|Moving Branch;Dragon Fin;Cursed Doll;Crystal Skull;Small Crystal",
  "Staff|Algernon|91|Moving Branch;Ambrosia's Thorns;Wind Dragon Tooth;Charm Blue;Lamp Grass",
  "Staff|Sorcerer's Wand|99|Rune Sphere Shard;Dragon Fin;Rune Crystal;Small Crystal;Moving Branch",
  "Staff|Basket|4|Strings;Strings;Cloths and Skins",
  "Staff|Golden Turnip Staff|80|Golden Turnip;Sticks and Stems",
  "Staff|Sweet Potato Staff|10|Sweet Potato;Sticks and Stems",
  "Staff|Elvish Harp|24|Strings;Sticks and Stems",
  "Staff|Syringe|29|Silver;Furs;Sticks and Stems",

  // Forging — tools
  "Tool|Cheap Hoe|5|Minerals",
  "Tool|Sturdy Hoe|15|Bronze",
  "Tool|Seasoned Hoe|30|Silver",
  "Tool|Shiny Hoe|45|Gold",
  "Tool|Blessed Hoe|80|Platinum",
  "Tool|Cheap Waterpot|5|Minerals;Cloths and Skins",
  "Tool|Tin Waterpot|15|Bronze;Cloths and Skins",
  "Tool|Lion Waterpot|30|Silver;Cloths and Skins",
  "Tool|Rainbow Waterpot|45|Gold;Cloths and Skins",
  "Tool|Joy Waterpot|80|Platinum;Cloths and Skins",
  "Tool|Cheap Sickle|5|Minerals;Shards",
  "Tool|Iron Sickle|15|Bronze;Shards",
  "Tool|Quality Sickle|30|Silver;Shards",
  "Tool|Super Sickle|45|Gold;Shards",
  "Tool|Legendary Sickle|80|Platinum;Shards",
  "Tool|Cheap Axe|5|Stones;Sticks and Stems",
  "Tool|Chopping Axe|15|Bronze;Stones;Sticks and Stems",
  "Tool|Lumber Axe|30|Silver;Stones;Sticks and Stems",
  "Tool|Mountain Axe|45|Gold;Stones;Sticks and Stems",
  "Tool|Miracle Axe|80|Platinum;Stones;Sticks and Stems",
  "Tool|Cheap Hammer|5|Minerals;Sticks and Stems",
  "Tool|Iron Hammer|15|Bronze;Sticks and Stems",
  "Tool|Silver Hammer|30|Silver;Sticks and Stems",
  "Tool|Golden Hammer|45|Gold;Sticks and Stems",
  "Tool|Platinum Hammer|80|Platinum;Sticks and Stems",
  "Tool|Cheap Pole|5|Sticks and Stems;Strings",
  "Tool|Beginner's Pole|15|Bronze;Sticks and Stems;Strings",
  "Tool|Skilled Pole|30|Silver;Sticks and Stems;Strings",
  "Tool|Famous Pole|45|Gold;Sticks and Stems;Strings",
  "Tool|Sacred Pole|80|Platinum;Sticks and Stems;Strings",

  // Crafting — accessories
  "Accessory|Yarn|6|Furs",
  "Accessory|Engagement Ring|20|Minerals;Jewels",
  "Accessory|Cheap Bracelet|5|Minerals",
  "Accessory|Bronze Bracelet|10|Bronze;Cloths and Skins",
  "Accessory|Silver Bracelet|25|Silver;Cloths and Skins",
  "Accessory|Gold Bracelet|39|Gold;Cloths and Skins",
  "Accessory|Platinum Bracelet|50|Platinum;Cloths and Skins",
  "Accessory|Silver Ring|24|Silver;Crystals",
  "Accessory|Gold Ring|63|Orichalcum;Gold;Turnip's Miracle",
  "Accessory|Platinum Ring|75|Dragonic Stone;Platinum",
  "Accessory|Shield Ring|44|Blk. Tortoise Shell;Turtle Shell;Minerals",
  "Accessory|Critical Ring|30|Gold;Rigid Horn",
  "Accessory|Silent Ring|29|Silver;Lamp Squid",
  "Accessory|Paralysis Ring|28|Silver;Scorpion Tail",
  "Accessory|Poison Ring|27|Silver;Poison Powder",
  "Accessory|Magic Ring|51|Platinum;Crystals",
  "Accessory|Throwing Ring|33|Puppetry Strings;Minerals",
  "Accessory|Stay-Up Ring|46|Holy Spore;Minerals",
  "Accessory|Aquamarine Ring|15|Silver;Aquamarine",
  "Accessory|Amethyst Ring|15|Silver;Amethyst",
  "Accessory|Emerald Ring|15|Silver;Emerald",
  "Accessory|Sapphire Ring|15|Silver;Sapphire",
  "Accessory|Ruby Ring|15|Silver;Ruby",
  "Accessory|Cursed Ring|15|Silver;Shells and Bones",
  "Accessory|Diamond Ring|60|Orichalcum;Diamond",
  "Accessory|Aquamarine Brooch|55|Platinum;Aquamarine",
  "Accessory|Amethyst Brooch|55|Platinum;Amethyst",
  "Accessory|Emerald Brooch|55|Platinum;Emerald",
  "Accessory|Sapphire Brooch|55|Platinum;Sapphire",
  "Accessory|Ruby Brooch|55|Platinum;Ruby",
  "Accessory|Diamond Brooch|77|Orichalcum;Light Ore;Rune Crystal;Diamond",
  "Accessory|Dolphin Brooch|88|White Stone;Orichalcum",
  "Accessory|Fire Ring|95|Orichalcum;Fire Crystal",
  "Accessory|Wind Ring|93|Orichalcum;Wind Crystal",
  "Accessory|Water Ring|96|Orichalcum;Water Crystal",
  "Accessory|Earth Ring|94|Orichalcum;Earth Crystal",
  "Accessory|Happy Ring|30|Silver;4-Leaf Clover",
  "Accessory|Silver Pendant|20|Silver",
  "Accessory|Star Pendant|40|Silver Pendant;Gold;Love Crystal",
  "Accessory|Sun Pendant|45|Silver Pendant;Gold;Fire Crystal",
  "Accessory|Field Pendant|35|Silver Pendant;Gold;Wind Crystal",
  "Accessory|Dew Pendant|28|Silver Pendant;Gold;Water Crystal",
  "Accessory|Earth Pendant|19|Silver Pendant;Gold;Earth Crystal",
  "Accessory|Heart Pendant|40|Silver Pendant;Love Crystal",
  "Accessory|Strange Pendant|85|Amethyst;Ruby;Minerals",
  "Accessory|Anette's Necklace|80|Rune Sphere Shard;Ancient Orc Cloth;Strings",
  "Accessory|Work Gloves|4|Cloths and Skins",
  "Accessory|Gloves|18|Giant's Gloves",
  "Accessory|Power Gloves|42|Giant's Gloves;Blue Giant's Glove",
  "Accessory|Earrings|8|Iron;Powders and Spores",
  "Accessory|Witch Earrings|30|Gold;Emerald;Mysterious Powder",
  "Accessory|Magic Earrings|45|Diamond;Ruby;Minerals",
  "Accessory|Charm|3|Cloths and Skins;Strings",
  "Accessory|Holy Amulet|55|Platinum;Diamond",
  "Accessory|Rosary|68|Silver;Puppetry Strings",
  "Accessory|Talisman|71|Rafflesia Petal;Ambrosia's Thorns;Strings",
  "Accessory|Magic Charm|66|Round Stone;Turnip's Miracle;Powders and Spores;Crystals",
  "Accessory|Leather Belt|13|Cloths and Skins;Shards",
  "Accessory|Lucky Strike|78|Critical Ring;Tablet of Truth;Dangerous Scissors;Minerals",
  "Accessory|Champ Belt|58|Warrior's Proof;Proof of Rank;Cloths and Skins",
  "Accessory|Hand-Knit Scarf|43|Yarn;Yarn;Yarn;Yarn",
  "Accessory|Fluffy Scarf|96|Wooly Furball;Fur (S);Fur (M);Fur (L);Yarn",
  "Accessory|Hero's Proof|73|Chest Hair;Small Crystal;Rune Crystal",
  "Accessory|Proof of Wisdom|74|Moving Branch;Small Crystal;Rune Crystal",
  "Accessory|Art of Attack|91|Dragonic Stone;Throne of the Empire;Wind Dragon Tooth",
  "Accessory|Art of Defense|90|Dragonic Stone;Grimoire Scale;Broken Ice Wall",
  "Accessory|Art of Magic|92|Dragonic Stone;Chimera Tail;Melody Bottle",
  "Accessory|Badge|6|Shards",
  "Accessory|Courage Badge|99|Badge;Rune Sphere Shard;Rune Crystal",

  // Crafting — shields
  "Shield|Small Shield|2|Minerals",
  "Shield|Umbrella|6|Cloths and Skins;Strings;Sticks and Stems",
  "Shield|Iron Shield|8|Iron;Iron",
  "Shield|Monkey Plush|12|Yellow Down;Cloths and Skins;Cloths and Skins",
  "Shield|Round Shield|15|Bronze",
  "Shield|Turtle Shield|20|Turtle Shell;Bronze;Liquids",
  "Shield|Chaos Shield|25|Silver;Pretty Carapace",
  "Shield|Bone Shield|32|Gold;Shells and Bones",
  "Shield|Magic Shield|37|Gold;Silver;Mysterious Powder;Crystals",
  "Shield|Heavy Shield|41|Diamond;Shoulder Piece",
  "Shield|Platinum Shield|43|Platinum;Platinum;Blk. Tortoise Shell",
  "Shield|Kite Shield|50|Proof of Rank;Warrior's Proof;Platinum;Dragon Bones",
  "Shield|Knight Shield|54|Orichalcum;Grimoire Scale",
  "Shield|Element Shield|58|Yellow Feather;Green Core;Red Core;Yellow Core;Blue Core",
  "Shield|Magical Shield|65|Crimson Scale;Left Rock Shard;Right Rock Shard;Rune Crystal",
  "Shield|Prism Shield|78|Blue Scale;Glitter Scale;Crimson Scale;Light Ore;Small Crystal",
  "Shield|Rune Shield|94|Dragonic Stone;Dragon Fin;Earthwyrm Scale;Rune Crystal;Small Crystal",

  // Crafting — headgear
  "Headgear|Headband|2|Cloths and Skins",
  "Headgear|Blue Ribbon|4|Blue Grass;Cloths and Skins;Strings",
  "Headgear|Green Ribbon|5|Green Grass;Cloths and Skins;Strings",
  "Headgear|Purple Ribbon|6|Purple Grass;Cloths and Skins;Strings",
  "Headgear|Spectacles|7|Aquamarine;Aquamarine",
  "Headgear|Straw Hat|8|Strings;Strings",
  "Headgear|Fancy Hat|9|Cloths and Skins;Strings",
  "Headgear|Brand Glasses|11|Dark Crystal;Aquamarine;Aquamarine",
  "Headgear|Cute Knitting|13|Cloths and Skins;Cloths and Skins",
  "Headgear|Intelligent Glasses|15|Magic Crystal;Aquamarine;Aquamarine",
  "Headgear|Fireproof Hood|16|Ghost Hood;Cloths and Skins",
  "Headgear|Silk Hat|17|Black Grass;Cloths and Skins",
  "Headgear|Black Ribbon|18|Black Grass;Cloths and Skins;Strings",
  "Headgear|Lolita Headdress|19|Black Grass;Cloths and Skins;Cloths and Skins;Strings",
  "Headgear|Headdress|20|Cloths and Skins;Cloths and Skins;Cloths and Skins;Strings",
  "Headgear|Yellow Ribbon|22|Yellow Grass;Cloths and Skins;Strings",
  "Headgear|Cat Ears|24|Furs",
  "Headgear|Silver Hairpin|26|Silver",
  "Headgear|Red Ribbon|30|Red Grass;Cloths and Skins;Strings",
  "Headgear|Orange Ribbon|35|Orange Grass;Cloths and Skins;Strings",
  "Headgear|White Ribbon|38|White Grass;Cloths and Skins;Strings",
  "Headgear|Four Seasons|44|Spring Headdress;Summer Headdress;Autumn Headdress;Winter Headdress",
  "Headgear|Feathered Hat|51|Quality Worn Cloth;Feathers;Strings",
  "Headgear|Gold Hairpin|60|Turnip's Miracle;Gold",
  "Headgear|Indigo Ribbon|77|Blue Scale;Indigo Grass;Cloths and Skins;Strings",
  "Headgear|Crown|95|Dragonic Stone;Small Crystal;Black Scale;White Stone;Rune Crystal",
  "Headgear|Turnip Headgear|30|Turnip",
  "Headgear|Pumpkin Headgear|20|Pumpkin",

  // Crafting — shoes
  "Shoes|Leather Boots|6|Furs",
  "Shoes|Free Farming Shoes|8|Strings;Furs",
  "Shoes|Piyo Sandals|11|Insect Carapace;Cloths and Skins",
  "Shoes|Secret Shoes|14|Glue;Minerals",
  "Shoes|Silver Boots|18|Silver;Shards",
  "Shoes|Heavy Boots|20|Silver;Iron;Pretty Carapace",
  "Shoes|Sneaking Boots|23|Invisible Stone;Cloths and Skins;Strings",
  "Shoes|Fast Step Boots|26|Root;Sapphire;Furs",
  "Shoes|Gold Boots|28|Gold;Gold;Shards",
  "Shoes|Bone Boots|33|Strong Vine;Big Crystal;Shells and Bones",
  "Shoes|Snow Boots|37|Shoulder Piece;Lightning Mane;Ambrosia's Thorns",
  "Shoes|Strider Boots|40|Pretty Thread;Platinum;Gold;Cloths and Skins",
  "Shoes|Step-In Boots|48|Warrior's Proof;Shiny Screw;Cloths and Skins;Strings",
  "Shoes|Feather Boots|54|Orichalcum;Big Bird's Comb;Big Crystal;Feathers;Strings",
  "Shoes|Ghost Boots|65|Quality Worn Cloth;Dragon Scale;Crimson Scale;Crystal Skull;Strings",
  "Shoes|Iron Geta|70|Dangerous Scissors;MTGU Plate;MTGU Plate;Iron;Iron",
  "Shoes|Knight Boots|86|Dragonic Stone;Black Scale;Ammonite;Strings",
  "Shoes|Fairy Boots|95|Earthwyrm Scale;Small Crystal;Melody Bottle;Strings;Feathers",
  "Shoes|Wet Boots|20|Scales;Scales",
  "Shoes|Water Shoes|75|Pretty Thread;Sticks and Stems;Cloths and Skins;Furs",
  "Shoes|Ice Skates|79|Broken Ice Wall;Cloths and Skins;Strings",
  "Shoes|Rocket Wing|99|Dragon Fin;Earthwyrm Scale;Firewyrm Scale;Wind Dragon Tooth;Feathers",

  // Crafting — armor
  "Armor|Shirt|2|Cloths and Skins",
  "Armor|Vest|8|Cloths and Skins;Furs",
  "Armor|Cotton Cloth|12|Old Bandage;Old Bandage;Spider's Thread",
  "Armor|Mail|16|Bronze;Liquids",
  "Armor|Chain Mail|20|Silver;Strings",
  "Armor|Scale Vest|25|Silver;Pretty Carapace;Root",
  "Armor|Sparkling Shirt|28|Gold;Furs;Cloths and Skins",
  "Armor|Wind Cloak|32|Black Bird Feather;Wind Crystal;Emerald;Cloths and Skins;Strings",
  "Armor|Protector|38|Shoulder Piece;Diamond",
  "Armor|Platinum Mail|44|Platinum;Platinum;Blk. Tortoise Shell;Cloths and Skins",
  "Armor|Lamellar Vest|50|Orichalcum;Scales;Strings",
  "Armor|Mercenary's Cloak|53|Quality Worn Cloth;Big Bird's Comb;Puppetry Strings",
  "Armor|Wooly Shirt|56|Electro Crystal;Wooly Furball;Wooly Furball;Strings",
  "Armor|Elvish Cloak|59|Turnip's Miracle;Ambrosia's Thorns;Crystal Skull;Powders and Spores",
  "Armor|Dragon Cloak|64|Dragon Scale;Crimson Scale;Grimoire Scale;Earth Dragon Ash;Strings",
  "Armor|Power Protector|69|Orichalcum;Orichalcum;Orichalcum;MTGU Plate;Dangerous Scissors",
  "Armor|Rune Vest|76|Golem Spirit Stone;Rune Crystal;Rune Crystal;Cloths and Skins;Strings",
  "Armor|Royal Garter|90|Dragonic Stone;Ancient Orc Cloth;Love Scale;Small Crystal;White Stone",
  "Armor|Four Dragons' Vest|99|Dragon Fin;Earthwyrm Scale;Firewyrm Scale;Wind Dragon Tooth;Rune Crystal",
] as const;
